# -*- coding: utf-8 -*-
"""Practical 8.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSSXnOHUPYXCpZIZlzzQr6X4rGMS8VyE
"""

#bfs code
from collections import deque

graph = {
    "A": ["B", "C"],
    "B": ["A", "D", "E"],
    "C": ["A", "F"],
    "D": ["B"],
    "E": ["B"],
    "F": ["C"]
}


def bfs(start):
    visited = set()
    queue = deque()

    visited.add(start)
    queue.append(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=" ")

        for neighbour in graph[vertex]:
            if neighbour not in visited:
                visited.add(neighbour)
                queue.append(neighbour)


print("BFS Traversal:")
bfs("A")

#dfs code
graph = {
    "A": ["B", "C"],
    "B": ["A", "D", "E"],
    "C": ["A", "F"],
    "D": ["B"],
    "E": ["B"],
    "F": ["C"]
}


def dfs(vertex, visited):
    visited.add(vertex)
    print(vertex, end=" ")

    for neighbour in graph[vertex]:
        if neighbour not in visited:
            dfs(neighbour, visited)


visited = set()

print("DFS Traversal:")
dfs("A", visited)

