# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pprwPKK5C4pSjp-iNsmz0Hp5t83uprn
"""

print("Enter weights of the items:")
for i in range(n):# 0/1 Knapsack using Dynamic Programming

# User input
n = int(input("Enter number of items: "))

weight = []
value = []

    weight.append(int(input(f"Weight of item {i + 1}: ")))

print("Enter values of the items:")
for i in range(n):
    value.append(int(input(f"Value of item {i + 1}: ")))

capacity = int(input("Enter capacity of knapsack: "))

# Create DP table
dp = [[0 for _ in range(capacity + 1)] for _ in range(n + 1)]

# Dynamic Programming
for i in range(1, n + 1):
    for w in range(1, capacity + 1):

        if weight[i - 1] <= w:
            dp[i][w] = max(
                value[i - 1] + dp[i - 1][w - weight[i - 1]],
                dp[i - 1][w]
            )
        else:
            dp[i][w] = dp[i - 1][w]

# Maximum value
print("\nMaximum value:", dp[n][capacity])

# Find selected items
w = capacity
selected_items = []

for i in range(n, 0, -1):
    if dp[i][w] != dp[i - 1][w]:
        selected_items.append(i)
        w -= weight[i - 1]

print("Selected items:", selected_items[::-1])

