# -*- coding: utf-8 -*-
"""Practical_6.cpp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugQ5WHPXt_CJivJAJxZ1tEnLHV-6W4C0
"""

import time

# Matrix Chain Multiplication using Dynamic Programming
def matrix_chain_order(p):
    n = len(p) - 1

    # dp[i][j] stores minimum multiplication cost
    dp = [[0] * n for _ in range(n)]

    # split[i][j] stores the position where the chain is split
    split = [[0] * n for _ in range(n)]

    # Chain length
    for length in range(2, n + 1):
        for i in range(n - length + 1):
            j = i + length - 1
            dp[i][j] = float('inf')

            for k in range(i, j):
                cost = (
                    dp[i][k]
                    + dp[k + 1][j]
                    + p[i] * p[k + 1] * p[j + 1]
                )

                if cost < dp[i][j]:
                    dp[i][j] = cost
                    split[i][j] = k

    return dp, split


# Construct optimal parenthesization
def print_optimal_parenthesis(split, i, j):
    if i == j:
        return f"M{i + 1}"

    k = split[i][j]

    left = print_optimal_parenthesis(split, i, k)
    right = print_optimal_parenthesis(split, k + 1, j)

    return f"({left} × {right})"


# -------- User Input --------

n = int(input("Enter the number of matrices: "))

print("Enter the dimensions of the matrices.")

# Example:
# A1 = 10 x 20
# A2 = 20 x 30
# A3 = 30 x 40
# Enter: 10 20 30 40

p = list(map(int, input(
    "Enter dimensions separated by spaces: "
).split()))

if len(p) != n + 1:
    print("Error: Enter exactly", n + 1, "dimensions.")
else:
    # Measure execution time
    start_time = time.perf_counter()

    dp, split = matrix_chain_order(p)

    end_time = time.perf_counter()

    execution_time = end_time - start_time

    print("\nMinimum number of scalar multiplications:",
          dp[0][n - 1])

    print("Optimal Parenthesization:",
          print_optimal_parenthesis(split, 0, n - 1))

    print("Execution Time: {:.9f} seconds".format(execution_time))

    print("\nTime Complexity: O(n^3)")
    print("Space Complexity: O(n^2)")